#!/bin/bash
set -e

DB_USER=${DB_USER:-odoo16}
DB_PASSWORD=${DB_PASSWORD:-odoo16}
DB_NAME=${DB_NAME:-odoo16}

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" << EOF 
    CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASSWORD}';
    CREATE DATABASE ${DB_NAME} WITH OWNER ${DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOF